language: go

go:
  - 1.13.4

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - go get -t -v ./...

script:
  - go test -v ./... -race -coverprofile=coverage.txt.tmp -covermode=atomic
  - cat coverage.txt.tmp | grep -v "app/models/*" > coverage.txt
  - rm coverage.txt.tmp

after_success:
  - bash <(curl -s https://codecov.io/bash)
