language: go

go:
  - 1.13.4

cache:
  directories:
    - $GOPATH/pkg/mod

before_install:
  - go get -t -v ./...

script:
  - bash skip_test.sh
  - APP_ENV=test go test -short -v ./... -race -coverprofile=coverage.txt.tmp -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
