// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Migrations", testMigrations)
	t.Run("Rounds", testRounds)
	t.Run("Scripts", testScripts)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Migrations", testMigrationsDelete)
	t.Run("Rounds", testRoundsDelete)
	t.Run("Scripts", testScriptsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Migrations", testMigrationsQueryDeleteAll)
	t.Run("Rounds", testRoundsQueryDeleteAll)
	t.Run("Scripts", testScriptsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Migrations", testMigrationsSliceDeleteAll)
	t.Run("Rounds", testRoundsSliceDeleteAll)
	t.Run("Scripts", testScriptsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Migrations", testMigrationsExists)
	t.Run("Rounds", testRoundsExists)
	t.Run("Scripts", testScriptsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Migrations", testMigrationsFind)
	t.Run("Rounds", testRoundsFind)
	t.Run("Scripts", testScriptsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Migrations", testMigrationsBind)
	t.Run("Rounds", testRoundsBind)
	t.Run("Scripts", testScriptsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Migrations", testMigrationsOne)
	t.Run("Rounds", testRoundsOne)
	t.Run("Scripts", testScriptsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Migrations", testMigrationsAll)
	t.Run("Rounds", testRoundsAll)
	t.Run("Scripts", testScriptsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Migrations", testMigrationsCount)
	t.Run("Rounds", testRoundsCount)
	t.Run("Scripts", testScriptsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Migrations", testMigrationsHooks)
	t.Run("Rounds", testRoundsHooks)
	t.Run("Scripts", testScriptsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Migrations", testMigrationsInsert)
	t.Run("Migrations", testMigrationsInsertWhitelist)
	t.Run("Rounds", testRoundsInsert)
	t.Run("Rounds", testRoundsInsertWhitelist)
	t.Run("Scripts", testScriptsInsert)
	t.Run("Scripts", testScriptsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Migrations", testMigrationsReload)
	t.Run("Rounds", testRoundsReload)
	t.Run("Scripts", testScriptsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Migrations", testMigrationsReloadAll)
	t.Run("Rounds", testRoundsReloadAll)
	t.Run("Scripts", testScriptsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Migrations", testMigrationsSelect)
	t.Run("Rounds", testRoundsSelect)
	t.Run("Scripts", testScriptsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Migrations", testMigrationsUpdate)
	t.Run("Rounds", testRoundsUpdate)
	t.Run("Scripts", testScriptsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Migrations", testMigrationsSliceUpdateAll)
	t.Run("Rounds", testRoundsSliceUpdateAll)
	t.Run("Scripts", testScriptsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
