name: Go
on: [push]
jobs:
  test:
    name: Test

    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: $GOPATH/pkg/mod
        # An explicit key for restoring and saving the cache
        key: modules

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Remove sqlboiler test
      run: rm app/models/*_test.go
        
    - name: Test
      run: go test -short -v ./... -race -coverprofile=coverage.txt.tmp -covermode=atomic
      env:
        APP_ENV: test 

    - name: Upload to codecov
      if: startsWith(matrix.os,'ubuntu')
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        fail_ci_if_error: true #optional (default = false)
